"""Declarative base bound to the `medvault` schema.

All ORM models inherit from Base, so its MetaData is what alembic diffs against
for FUTURE autogenerated migrations (env.py imports it as target_metadata). The
hand-written baseline migrations (0001-0007) are the source of truth for the
initial schema, RLS, functions and grants — autogenerate cannot express those.
"""
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Stable, explicit constraint/index names so autogenerated diffs are reproducible.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(schema="medvault", naming_convention=NAMING_CONVENTION)


# Convenience export for env.py: `from app.models import metadata`.
metadata = Base.metadata
